#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 4.0.0-{branch}-{build}

branches:
  only:
    - master

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  versionnumber: 3.27
  SERVER_TARGET: netcoreapp5.0
  GUI_TARGET: net5.0-windows
  sonarcloudtoken:
    secure: VMTLc0vSBXvIH5sBuyKY6ri8IL3I5kYpXnCK3xYPkfXK0+tFnIwlotzE3Gn5Yu4u

image: Visual Studio 2019

init:
  - git config --global core.autocrlf input

install:

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release

before_build:
  - ps: Install-Product node lts
  
build_script:
  - cmd: cd Web && npm install
  - ps: .\ci.ps1 -version $env:versionnumber
  - ps: |
      7z a XOutput.zip -- `
      $PSScriptRoot\XOutput.Core\bin\Release\$env:SERVER_TARGET\XOutput.Core.dll `
      $PSScriptRoot\XOutput.Core\bin\Release\$env:SERVER_TARGET\NLog.dll `
      $PSScriptRoot\XOutput.Api\bin\Release\$env:SERVER_TARGET\XOutput.Api.dll `
      $PSScriptRoot\XOutput.Emulation\bin\Release\$env:SERVER_TARGET\XOutput.Emulation.dll `
      $PSScriptRoot\XOutput.Emulation\bin\Release\$env:SERVER_TARGET\Nefarius.ViGEm.Client.dll `
      $PSScriptRoot\XOutput.Mapping\bin\Release\$env:SERVER_TARGET\XOutput.Mapping.dll `
      $PSScriptRoot\XOutput.Server\bin\Release\$env:SERVER_TARGET\XOutput.Server.dll `
      $PSScriptRoot\XOutput.Server\bin\Release\$env:SERVER_TARGET\XOutput.Server.exe `
      $PSScriptRoot\XOutput.Server\bin\Release\$env:SERVER_TARGET\XOutput.Server.runtimeconfig.json `
      $PSScriptRoot\XOutput.App\bin\Release\$env:GUI_TARGET\XOutput.App.dll `
      $PSScriptRoot\XOutput.App\bin\Release\$env:GUI_TARGET\XOutput.App.exe `
      $PSScriptRoot\XOutput.App\bin\Release\$env:GUI_TARGET\XOutput.App.runtimeconfig.json `
      $PSScriptRoot\XOutput.App\bin\Release\$env:GUI_TARGET\SharpDX.dll `
      $PSScriptRoot\XOutput.App\bin\Release\$env:GUI_TARGET\SharpDX.DirectInput.dll `
      $PSScriptRoot\XOutput.App\bin\Release\$env:GUI_TARGET\Hardcodet.Wpf.TaskbarNotification.dll `
      $PSScriptRoot\XOutput.App\bin\Release\$env:GUI_TARGET\HIDSharp.dll `
      $PSScriptRoot\Web\webapp `
      $PSScriptRoot\bin\*

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: XOutput.zip
    name: XOutput

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:

#---------------------------------#
#        global handlers          #
#---------------------------------#

on_success:

on_failure:

on_finish:


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Email
    to:
      - csutorasa@gmail.com
    on_build_success: false
