#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 3.27-{branch}-{build}

branches:
  only:
    - master

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  versionnumber: 3.27
  sonarcloudtoken:
    secure: VMTLc0vSBXvIH5sBuyKY6ri8IL3I5kYpXnCK3xYPkfXK0+tFnIwlotzE3Gn5Yu4u

image: Visual Studio 2019

init:
  - git config --global core.autocrlf input

install:

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release
  
build_script:
  - cmd: cd Web && npm install
  - ps: dotnet tool install --global dotnet-sonarscanner
  - ps: dotnet sonarscanner begin /k:"XOutput" /d:"sonar.host.url=https://sonarcloud.io" /o:"csutorasa" /d:"sonar.login=$env:sonarcloudtoken" /d:sonar.cs.opencover.reportsPaths="*Tests\coverage.*.opencover.xml" /d:sonar.coverage.exclusions="**Tests*.cs,**/NativeMethods.cs,**/*Configuration.cs"
  - ps: dotnet msbuild -p:Configuration=Release -p:Version=$env:versionnumber -p:AssemblyVersion=$env:versionnumber -p:FileVersion=$env:versionnumber
#  - ps: dotnet build -c Release -p:Version=$env:versionnumber -p:AssemblyVersion=$env:versionnumber -p:FileVersion=$env:versionnumber

before_build:
  - ps: Install-Product node lts
  - ps: dotnet restore
  
after_build:
  - ps: 7z a XOutput.zip $env:APPVEYOR_BUILD_FOLDER\XOutput.Core\bin\Release\net452\XOutput.Core.dll $env:APPVEYOR_BUILD_FOLDER\XOutput.Core\bin\Release\net452\Newtonsoft.Json.dll $env:APPVEYOR_BUILD_FOLDER\XOutput.Core\bin\Release\net452\NLog.dll $env:APPVEYOR_BUILD_FOLDER\XOutput.Api\bin\Release\net452\XOutput.Api.dll $env:APPVEYOR_BUILD_FOLDER\XOutput.Input\bin\Release\net452\XOutput.Input.dll $env:APPVEYOR_BUILD_FOLDER\XOutput.Server\bin\Release\net452\XOutput.Server.exe $env:APPVEYOR_BUILD_FOLDER\XOutput.Server\bin\Release\net452\Nefarius.ViGEm.Client.dll $env:APPVEYOR_BUILD_FOLDER\XOutput\bin\Release\net452\XOutput.exe $env:APPVEYOR_BUILD_FOLDER\XOutput\bin\Release\net452\SharpDX.dll $env:APPVEYOR_BUILD_FOLDER\XOutput\bin\Release\net452\SharpDX.DirectInput.dll $env:APPVEYOR_BUILD_FOLDER\XOutput\bin\Release\net452\Hardcodet.Wpf.TaskbarNotification.dll $env:APPVEYOR_BUILD_FOLDER\Web\webapp

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - ps: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_test:
  - ps: dotnet sonarscanner end /d:"sonar.login=$env:sonarcloudtoken"

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: XOutput.zip
    name: XOutput

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:

#---------------------------------#
#        global handlers          #
#---------------------------------#

on_success:

on_failure:

on_finish:


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Email
    to:
      - csutorasa@gmail.com
    on_build_success: false
