#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 3.27-{branch}-{build}

branches:
  only:
    - master

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  versionnumber: 3.27
  sonarCloudToken:
    secure: VMTLc0vSBXvIH5sBuyKY6ri8IL3I5kYpXnCK3xYPkfXK0+tFnIwlotzE3Gn5Yu4u

image: Visual Studio 2019

init:
  - git config --global core.autocrlf input

install:

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release
  
build_script:
  - cmd: cd Web && npm install && cd ..
  - ps: dotnet tool install --global dotnet-sonarscanner
  - ps: dotnet sonarscanner begin /k:"XOutput" /d:sonar.host.url=https://sonarcloud.io /o:csutorasa /d:sonar.login=$sonarCloudToken /d:sonar.cs.opencover.reportsPaths=*Tests\coverage.*.opencover.xml /d:sonar.coverage.exclusions=**Tests*.cs,**/*Configuration.cs
  - ps: dotnet msbuild -p:Configuration=Release -p:Version=$versionnumber -p:AssemblyVersion=$versionnumber -p:FileVersion=$versionnumber
#  - ps: dotnet build -c Release -p:Version=$versionnumber -p:AssemblyVersion=$versionnumber -p:FileVersion=$versionnumber

before_build:
  - ps: Install-Product node lts
  - ps: dotnet restore
  
after_build:
  - cmd: 7z a XOutput.zip %APPVEYOR_BUILD_FOLDER%\XOutput.Core\bin\Release\net452\XOutput.Core.dll %APPVEYOR_BUILD_FOLDER%\XOutput.Core\bin\Release\net452\Newtonsoft.Json.dll %APPVEYOR_BUILD_FOLDER%\XOutput.Core\bin\Release\net452\NLog.dll %APPVEYOR_BUILD_FOLDER%\XOutput.Api\bin\Release\net452\XOutput.Api.dll %APPVEYOR_BUILD_FOLDER%\XOutput.Server\bin\Release\net452\XOutput.Server.* %APPVEYOR_BUILD_FOLDER%\XOutput.Server\bin\Release\net452\Nefarius.ViGEm.Client.dll %APPVEYOR_BUILD_FOLDER%\XOutput\bin\Release\net452\XOutput.* %APPVEYOR_BUILD_FOLDER%\XOutput\bin\Release\net452\SharpDX.dll %APPVEYOR_BUILD_FOLDER%\XOutput\bin\Release\net452\SharpDX.DirectInput.dll %APPVEYOR_BUILD_FOLDER%\XOutput\bin\Release\net452\Hardcodet.Wpf.TaskbarNotification.dll %APPVEYOR_BUILD_FOLDER%\Web\dist\*

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - ps: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_test:
  - ps: dotnet sonarscanner end /d:sonar.login=$sonarCloudToken

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: XOutput.zip
    name: XOutput

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:

#---------------------------------#
#        global handlers          #
#---------------------------------#

on_success:

on_failure:

on_finish:


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Email
    to:
      - csutorasa@gmail.com
    on_build_success: false
