#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 4.0.0-{branch}-{build}

branches:
  only:
    - master

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  versionnumber: 3.27
  sonarcloudtoken:
    secure: VMTLc0vSBXvIH5sBuyKY6ri8IL3I5kYpXnCK3xYPkfXK0+tFnIwlotzE3Gn5Yu4u

image: Visual Studio 2019

init:
  - git config --global core.autocrlf input

install:

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release
  
build_script:
  - cmd: cd Web && npm install
  - ps: .\ci.ps1 -version $env:versionnumber

before_build:
  - ps: Install-Product node lts

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: XOutput.zip
    name: XOutput

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:

#---------------------------------#
#        global handlers          #
#---------------------------------#

on_success:

on_failure:

on_finish:


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Email
    to:
      - csutorasa@gmail.com
    on_build_success: false
